second_win - zira
class TestWin(QWidget):
  def_init_(self):
  super()._init_()
  self.initUI()
  self.connects() #tambahkan
  sellf.set_appear()
  self.show()
def next_click(self): #tambahkan
  self.tw = TestWin()
  self.hide()
def connects(self): #tambahkan
  self.btn_next.click.connect(self.next_click)
def set_appear(self): #tambahkan
  self.setWindowTitle(txt_title)
  self.resize(wn_width, win_height)
  self.move(win_x, win_y)
def initUI(self): #tambahkan
  self.btn_next = QPushButton(txt_sendresults, self)
  self.btn_test1 = QPushButton(txt_startest1, self)
  self.btn_test2 = QPushButton(txt_startest2, self)
  self.btn_test3 = QPushButton(txt_startest3, self)
  self.text_name = QLabel (txt_name)
  self.text_age = QLabel (txt_age)
  self.text_test1 = QLabel (txt_test1)
  self.text_test2 = QLabel (txt_test2)
  self.text_test3 = QLabel (txt_test3)
  self.text_timer = QLabel (txt_timer)
  self.line_name = QLineEdit(txt_hintname)
  self.line_age = QLineEdit(txt_hintage)
  self.line_test1 = QLineEdit(txt_hinttest1)
  self.line_test2 = QLineEdit(txt_hinttest2)
  self.line_test3 = QLineEdit(txt_hinttest3)
  self.l_lline = QVBoxLayout()
  self.r_lline = QVBoxLayout()
  self.h_lline = QHBoxLayout()
  self.r_line.addWidget(self.text_timer, alignment = Qt.AlignCenter)
  self.l_line.addWidget(self.text_name, alignment = Qt.AlignLeft)
  self.l_line.addWidget(self.line_name, alignment = Qt.AlignLeft)
  self.l_line.addWidget(self.text_age, alignment = Qt.AlignLeft)
  self.l_line.addWidget(self.line_name, alignment = Qt.AlignLeft)
  self.l_line.addWidget(self.text_test1, alignment = Qt.AlignLeft)
  self.l_line.addWidget(self.btn_test1, alignment = Qt.AlignLeft)
  self.l_line.addWidget(self.line_test1, alignment = Qt.AlignLeft)
  self.l_line.addWidget(self.text_test2, alignment = Qt.AlignLeft)
  self.l_line.addWidget(self.btn_test2, alignment = Qt.AlignLeft)
  self.l_line.addWidget(self.line_test2, alignment = Qt.AlignLeft)
  self.l_line.addWidget(self.text_test3, alignment = Qt.AlignLeft)
  self.l_line.addWidget(self.btn_test3, alignment = Qt.AlignLeft)
  self.l_line.addWidget(self.line_test3, alignment = Qt.AlignLeft)
  self.l_line.addWidget(self.btn_next, alignment = Qt.AlignCenter)
  self.h_line.addWidget(self.l_line)
  self.h_line.addWidget(self.r_line)
  self.setLayout(self.h_line)
